name: test our code on pull request
run-name: ${{ github.actor }} is testing TDDeter
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test_on_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout working repository
        uses: actions/checkout@v3
      - name: Install dependencies with package-lock
        run: npm ci
      - name: Run tests
        run: npm run test

      
